#!/bin/sh

echo "Testing with 3 numbers"
ARG=$(python test.py 3 | cut -c 2- | rev | cut -c2- | rev)
echo "Number of Movements"
./push_swap $ARG | wc -l

echo "Testing with 5 numbers"
ARG=$(python test.py 5 | cut -c 2- | rev | cut -c2- | rev)
echo "Number of Movements"
./push_swap $ARG | wc -l

echo "Testing with 100 numbers"
ARG=$(python test.py 100 | cut -c 2- | rev | cut -c2- | rev)
echo "Number of Movements"
./push_swap $ARG | wc -l

echo "Testing with 500 numbers"
ARG=$(python test.py 500 | cut -c 2- | rev | cut -c2- | rev)
echo "Number of Movements"
./push_swap $ARG | wc -l

echo "Testing with 1000 numbers"
ARG=$(python test.py 1000 | cut -c 2- | rev | cut -c2- | rev)
echo "Number of Movements"
./push_swap $ARG | wc -l